---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#playbooks-best-practices
- name: Run All The Things locally
  hosts: localhost
  connection: local
  become: yes
  roles:
    - bacula-client
    #- host-basics
