---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#playbooks-best-practices
- name: Run All The Things
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - host-basics
