---
# tasks file for host-basics

# Borrowed partly from https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#playbooks-best-practices
- name: be sure ntp is installed
  yum:
    name: ntp
    state: installed
  tags: ntp

- name: be sure ntpd is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

- name: be sure yum-cron is installed
  yum:
    name: yum-cron
    state: installed
  tags: yum-cron

- name: be sure yum-cron is running and enabled
  service:
    name: yum-cron
    state: started
    enabled: yes
  tags: yum-cron


# Thanks https://stackoverflow.com/a/29997722
- name: upgrade all packages
  yum: name=* state=latest
  
