---
# tasks file for host-basics
#
# Borrowed partly from https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#playbooks-best-practices

- name: be sure essential packages are installed
  yum:
    name:
      - ipa-client
      - at
      - git
      - ntp
      - pam_ssh_agent_auth
      - tmux
      - vim-enhanced
      - yum-cron
    state: installed
  tags: 
    - host-basics
    - at
    - ipa-client
    - git
    - pam_ssh_agent_auth
    - ntp
    - tmux
    - vim-enhanced
    - yum-cron

- name: be sure atd is running and enabled
  service:
    name: atd
    state: started
    enabled: yes
  tags: 
    - host-basics
    - at

- name: be sure ntpd is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: 
    - host-basics
    - ntp

- name: be sure yum-cron is running and enabled
  service:
    name: yum-cron
    state: started
    enabled: yes
  tags: 
    - host-basics
    - yum-cron

- name: Configure pam_ssh_agent_auth
  lineinfile:    
    path: /etc/pam.d/sudo
    regexp: '^auth *sufficient *pam_ssh_agent_auth.so'
    line: 'auth    sufficient     pam_ssh_agent_auth.so file=~/.ssh/authorized_keys'
    insertafter: '#%PAM-1.0'
  tags: 
    - host-basics
    - pam_ssh_agent_auth

