---
# tasks file for host-basics
#
# Borrowed partly from https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#playbooks-best-practices


# Thanks https://stackoverflow.com/a/29997722
- name: upgrade all packages
  yum: name=* state=latest
  
