---
# tasks file for bacula-client
#
# Borrowed partly from https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#playbooks-best-practices

- name: Install firewall
  include: firewall.yml

- name: Install bacula client daemon
  include: daemon.yml
